Neos:
  Flow:
#    security:
#      authentication:
#        providers:
#          'Neos.Neos:Backend':
#            requestPatterns:
#              'Neos.Neos.Ui:BackendControllers':
#                pattern: ControllerObjectName
#                patternOptions:
#                  controllerObjectNamePattern: 'Neos\Neos\Ui\Controller\.*'
    security:
      authentication:
        providers:
          JwtAuthProvider:
            provider: Sandstorm\NeosApi\Auth\JwtAuthProvider
    mvc:
      routes:
        'Sandstorm.NeosApi': {}
          #position: 'before Neos.Neos'

  Neos:
    Ui:
      resources:
        javascript:
          'Sandstorm.NeosApi':
            resource: 'resource://Sandstorm.NeosApi/Public/NeosApiUiAdjustments/Plugin.js'
            # esm supportÂ²
            # in case you want to use esbuild's code splitting (ESM only)
            # or just reference an ESM Plugin, set the type to module
            # attributes:
            #   type: module

        # optional if youre using css
        stylesheets:
          'Sandstorm.NeosApi':
            resource: 'resource://Sandstorm.NeosApi/Public/NeosApiUiAdjustments/Plugin.css'

      configurationDefaultEelContext:
        Sandstorm.NeosApi.Internal.UiAdjustments: Sandstorm\NeosApi\Internal\UiAdjustmentsHelper

      frontendConfiguration:
        'Sandstorm.NeosApi':
          showMainMenu: '${Sandstorm.NeosApi.Internal.UiAdjustments.showMainMenu()}'
          showLeftSideBar: '${Sandstorm.NeosApi.Internal.UiAdjustments.showLeftSideBar()}'


Sandstorm:
  NeosApi:
    Secret: '%env:NEOS_API_SECRET%'

